### ISSUE TITLE
TypeError: load() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by yangcheng001** [tadax/srgan#1]
thank you for upload the code of srgan.But when I run 'python vgg19/cifar_100/preprocess.py', I got this error:
Traceback (most recent call last):
  File "preprocess.py", line 50, in <module>
    data.preprocess()
  File "preprocess.py", line 32, in preprocess
    meta, train, test = self.load_pickle('raw')
  File "preprocess.py", line 41, in load_pickle
    train = pickle.load(f, encoding='latin-1')
TypeError: load() got an unexpected keyword argument 'encoding'

Can you help me?

**Comment by tadax** [comment]
Use Python 3 instead of 2.

**Comment by yangcheng001** [comment]
thanks for your help

**Comment by naveenfy** [comment]
Worked, thanks.
