### ISSUE TITLE
when running the 'train.py' in src, there are some errors.

### ISSUE THREAD

**Issue by DunguLock** [tadax/srgan#5]
These errors as follows:
File "/home/project/srgan-maset/src/train.py", line 87, in <module>
  train()
File "/home/project/srgan-maset/src/train.py", line 17, in train
  model = SRGAN()
File "/home/project/srgan-maset/src/srgan.py", line 19,  in __init__
  x = pixel_shuffle_layer(x, 2, 64)  
File "../utils/layer.py", line 71, in pixel_shuffle_layer
  xc = tf.split(3, n_split, x)
File “ home/anaconda2/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py”, line 3426, in _split
   num_split=num_split, name=name)
File "home/anaconda2/python2.7/site-pacakges/tensorflow/python/framework/op_def_library.py", line 509, in apply_op
   (prefix, dtype.as_type(input_arg.type.name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match except type int32.

I guess that this error is caused by using python2. Can you help me to do with this error? Thank you!
@tadax

**Comment by tadax** [comment]
This is because the order of parameters are different in previous versions of TensorFlow.

- for versions < 0.12.0
`tf.split(axis, num_or_size_splits, value)`

- for versions > 0.12.0
`tf.split(value, num_or_size_splits, axis)`

By the way, tf.concat need to be changed too.

- for versions < 0.12.0
`tf.concat(axis, values)`

- for versions > 0.12.0
`tf.concat(values, axis)`


Updated source code is coming soon.

**Comment by DunguLock** [comment]
many thanks!

**Comment by DunguLock** [comment]
The results that you put in this web seems not good, there always some bad  patches in the sr-images, have you do some work to this problem?

**Comment by DunguLock** [comment]
@tadax

**Comment by tadax** [comment]
I modified as follows.
- Fixed adversarial loss.
- Upgraded TF Version 0.9 to 1.1.
- Pretrained VGG19 with ImageNet dataset instead of CIFAR-100 dataset.

The result is a significant improvement over the previous one. See the [results](https://github.com/tadax/srgan/tree/master/results).

**Comment by DunguLock** [comment]
The results have improved a alot comparing to the old sr-images, but there are some blue point in these result as before. I think you should do some works on this problem! last, Thanks for your works and sharing!
